<?php namespace ProcessWire;

class ChatAIPromptService extends Wire {

    const PROMPT_TTL = 86400;

    protected $promptMemo = null;

    public function loadPromptSettings(bool $force = false): array
    {
        if (is_array($this->promptMemo)) return $this->promptMemo;

        $cache = $this->wire('cache');
        if ($force) $cache->deleteFor('chatai', 'promptSettings');

        $cfg = $cache->getFor('chatai', 'promptSettings', self::PROMPT_TTL, function () {
            $chatai = $this->wire('modules')->get('ChatAI');
            $db = $this->wire('database');
            $table = $chatai::dbTablePrompt;

            $stmt = $db->prepare("SELECT json FROM `$table` WHERE id = 1 LIMIT 1");
            $stmt->execute();
            $row = $stmt->fetch(\PDO::FETCH_ASSOC);

            if (!$row || !isset($row['json'])) return [];

            $cfg = json_decode($row['json'], true);
            return is_array($cfg) ? $cfg : [];
        });

        return $this->promptMemo = (is_array($cfg) ? $cfg : []);
    }

    public function getLanguageVal(string $name): string {
        $cfg = $this->loadPromptSettings();
        if(empty($cfg)) return '';

        $languages = $this->wire('languages');
        $user = $this->wire('user');

        if(!$languages || !$user->language || $user->language->isDefault()) {
            return (string) ($cfg[$name] ?? '');
        }

        $langId = (int) $user->language->id;
        $key = $name . '__' . $langId;

        if(!empty($cfg[$key])) return (string) $cfg[$key];
        return (string) ($cfg[$name] ?? '');
    }

    public function getIntro(): string {
        $botname = $this->getLanguageVal('botname');
        $botintro = $this->getLanguageVal('botintro');
        return str_ireplace('{botname}', $botname, (string) $botintro);
    }

    public function getPlaceholder(): string { return $this->getLanguageVal('input_placeholder'); }
    public function getButtonText(): string { return $this->getLanguageVal('submit_text'); }
    public function getResetText(): string { return $this->getLanguageVal('reset_text'); }
    public function getThinkingText(): string { return $this->getLanguageVal('thinking_text'); }
    public function getDisclaimerText(): string { return $this->getLanguageVal('disclaimer_text'); }
    public function getFooterText(): string { return $this->getLanguageVal('footer_text'); }
    public function getBotName(): string { return $this->getLanguageVal('botname'); }

    public function getPrompt(): string {
        return $this->buildPrompt();
    }

    protected function buildPrompt(): string
    {
        $modules = $this->wire('modules');
        $user    = $this->wire('user');

        $cfg = $this->loadPromptSettings();
        if (empty($cfg)) {
            return '';
        }

        // Custom prompt
        if ((int)($cfg['autogen'] ?? 1) === 0) {
            $txt = trim((string)($cfg['custom_prompt'] ?? ''));
            if ($txt !== '') return $txt;
        }

        // Autogenerated prompt expects variables present (mirrors your existing foreach)
        foreach ($cfg as $key => $value) {
            $$key = $value;
        }

        $botname = $this->getLanguageVal('botname');

        // Auto-generated prompt
        $langCode = ($user && $user->language) ? $user->language->name : 'en';
        $langs = [
            'en'    => 'English',
            'en-au' => 'Australian English',
            'es'    => 'Spanish',
            'fr'    => 'French',
            'de'    => 'German'
        ];

        if ($modules->isInstalled('Languages')) {
            foreach ($modules->get('Languages')->languages as $language) {
                $langs[$language->name] = $language->title;
            }
        }

        $langName = isset($langs[$langCode]) ? $langs[$langCode] : 'English';

        $counter = 1;

        $allowed = trim((string)($cfg['allowed_tags'] ?? 'p,ul,li,ol,strong,em,code,br,a[href],blockquote'));
        $allowedClean = array_values(array_filter(array_map('trim', explode(',', $allowed))));

        // Build literal tags for the PROMPT (not HTML-escaped)
        $allowedForPrompt = implode(', ', array_map(function ($t) {
            if (stripos($t, 'a[') === 0) return '<a href="">';
            return '<' . $t . '>';
        }, $allowedClean));

        $followup_terms = $followup_terms ?? '...';


        $prompt = '';

        // Assemble safe default system prompt
        if (!empty($botname)) {
            $prompt .= "You are {$botname}";
            if (!empty($botrole)) {
                $prompt .= ", {$botrole}";
                if (!empty($bizname)) {
                    $prompt .= " for {$bizname}";
                }
            }
            $prompt .= ".\n";
        }

        if (!empty($autohint)) {
            $prompt .= "\n{$autohint}";
        }

        // 1. Language Detection
        $prompt .= "\n{$counter}. **Language Detection**";
        $prompt .= "\n- Automatically detect and respond in the user's language. If the language is unclear, default to {$langName}\n";

        // 2. Tone and style
        if (!empty($tone)) {
            $counter++;
            $prompt .= "\n{$counter}. **Tone & Style**\n";
            $prompt .= "- Maintain a {$tone} tone.\n";
            $prompt .= "- Encourage users without excessive optimism.\n";
            $prompt .= "- Do not use emojis or em dashes.\n";
            $prompt .= "- Keep sentences clear, concise, and straightforward.\n";
            $prompt .= "- Do not identify yourself as {$botname} unless specifically asked.\n";
        }

        // 3. Output formatting
        $counter++;
        $prompt .= "\n{$counter}. **Output Formatting (HTML only)**";
        $prompt .= "\n- Use only these tags: {$allowedForPrompt}.";
        $prompt .= "\n- Output HTML fragments only. Do not include `<html>`, `<head>`, or `<body>`.";
        $prompt .= "\n- Do not include inline CSS, scripts, images, or tables.";
        $prompt .= "\n- Use `<p>` for paragraphs, lists with `<ul>/<ol>`, and `<br>` for simple line breaks.";
        $prompt .= "\n- Escape any user-supplied HTML unless specific formatting is requested. Treat input as plain text by default.";
        $prompt .= "\n- Create links with `<a href='...'>` using only absolute URLs and no other attributes.\n";

        // Safety & Civility
        $counter++;
        $prompt .= "\n{$counter}. **Safety & Civility**";
        $prompt .= "\n- Do not echo rude or obscene language. Respond politely and guide the conversation toward respect.";
        $prompt .= "\n- Decline any harmful or illegal requests succinctly and suggest safer alternatives.";
        $prompt .= "\n- Always acknowledge greetings and ask for what the user would like to know.\n";

        // Brevity
        $counter++;
        $prompt .= "\n{$counter}. **Brevity**";
        $words = !empty($botwords) ? $botwords : 400;
        $prompt .= "\n- Limit responses to approximately {$words} words.";
        $prompt .= "\n- When addressing broad topics, present essential information in short lists.";
        $prompt .= "\n- For greetings or casual conversation, respond naturally and conversationally without meta-commentary.\n";

        // Clarification & Uncertainty
        $counter++;
        $prompt .= "\n{$counter}. **Clarification & Uncertainty**";
        $prompt .= "\n- If critical details are missing, ask up to two brief clarifying questions.";
        $prompt .= "\n- If the user prefers no questions, act on reasonable assumptions and clearly state them.";
        $prompt .= "\n- If information is unavailable, acknowledge this briefly and suggest next steps or what details are needed.\n";

        // Additional Guidance
        $prompt .= "\n**Additional Guidance**";
        $prompt .= "\n- Only validate coverage when the user’s request is complex or multi-part.";
        $prompt .= "\n- Do not state “this covers your greeting” or similar for simple greetings or small talk.";
        $prompt .= "\n- Except when it is a greeting or small talk, if no site context is provided for the current question, reply briefly that no relevant on-site pages were found, then ask one specific clarifying question. Offer exactly one self-check tip. Do not mention browsing or technical limitations.";
        $prompt .= "\n- If you asked a clarifying question, interpret short replies such as {$followup_terms}, or a page title as answers to that question.";

        $prompt .= "\n";

        return $prompt;
    }

    public function getWidget(string $path): string {
        $files = $this->wire('files');

        return (string) $files->render($path, [
            'intro' => $this->getIntro(),
            'placeholder' => $this->getPlaceholder(),
            'button_text' => $this->getButtonText(),
            'reset_text' => $this->getResetText(),
            'thinking_text' => $this->getThinkingText(),
            'disclaimer_text' => $this->getDisclaimerText(),
            'footer_text' => $this->getFooterText(),
        ]);
    }

    public function isBlacklistTerm(string $message): bool {
        $sanitizer = $this->wire('sanitizer');
        $cfg = $this->loadPromptSettings();

        if(empty($cfg['use_blacklist']) || empty($cfg['blacklist'])) return false;

        $msg = mb_strtolower($sanitizer->text($message));
        if($msg === '') return false;

        $terms = array_filter(array_map('trim', explode(',', (string) $cfg['blacklist'])));

        foreach($terms as $t) {
            $t = mb_strtolower($sanitizer->text($t));
            if($t === '') continue;

            $pattern = '/\b' . preg_quote(str_replace(' ', '___SPACE___', $t), '/') . '\b/iu';
            $pattern = str_replace('___SPACE___', '\s+', $pattern);

            if(preg_match($pattern, $msg)) {
                $this->wire('log')->save('chatai-blacklist-debug', "Matched phrase '{$t}' in message: '{$msg}'");
                return true;
            }
        }

        return false;
    }

    public function savePromptSettings(array $cfg): bool
    {
        $chatai = $this->wire('modules')->get('ChatAI');
        if(!$chatai) return false;

        $json = json_encode($cfg, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
        if($json === false) return false;

        $db = $this->wire('database');
        $table = $chatai::dbTablePrompt;

        $stmt = $db->prepare("UPDATE `$table` SET json = :json WHERE id = 1 LIMIT 1");
        $stmt->bindValue(':json', $json, \PDO::PARAM_STR);

        $ok = $stmt->execute();

        if($ok) {
            $this->promptMemo = $cfg;
            $this->wire('cache')->saveFor('chatai', 'promptSettings', $cfg, self::PROMPT_TTL);
        }

        return (bool) $ok;
    }

}
